#ifndef REDIS_HOSTNAME
#define REDIS_HOSTNAME "REDIS_HOSTNAME"
#endif

#ifndef WIFI_SSID
#define WIFI_SSID "WIFI_SSID"
#endif

#ifndef WIFI_PASSWORD
#define WIFI_PASSWORD "WIFI_PASSWORD"
#endif

#ifndef MQTT_HOSTNAME
#define MQTT_HOSTNAME "MQTT_HOSTNAME"
#endif