name: build
on:
  workflow_run:
    workflows: [test]
    types: [completed]
env:
  branch: ${{ github.event.workflow_run.head_branch }}
  registry: ghcr.io
  image: ${{ github.repository }}
concurrency: build
jobs:
  api:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.branch }}
      - name: Build and push api Docker image
        uses: ./.github/actions/docker-build-push
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ env.image }}.api
          context: server
          target: api
          secrets: |
            NUGET_USERNAME=${{ secrets.NUGET_GITHUB_USER }}
            NUGET_PASSWORD=${{ secrets.NUGET_GITHUB_TOKEN }}
  worker:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.branch }}
      - name: Build and push worker Docker image
        uses: ./.github/actions/docker-build-push
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ env.image }}.worker
          context: server
          target: worker
          secrets: |
            NUGET_USERNAME=${{ secrets.NUGET_GITHUB_USER }}
            NUGET_PASSWORD=${{ secrets.NUGET_GITHUB_TOKEN }}
  migrations:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.branch }}
      - name: Build and push migrations Docker image
        uses: ./.github/actions/docker-build-push
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ env.image }}.migrations
          context: server
          target: migrations
          secrets: |
            NUGET_USERNAME=${{ secrets.NUGET_GITHUB_USER }}
            NUGET_PASSWORD=${{ secrets.NUGET_GITHUB_TOKEN }}
  app:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.branch }}
      - name: Build and push app Docker image
        uses: ./.github/actions/docker-build-push
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ env.image }}.app
          context: app
  client:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.branch }}
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install PlatformIO
        run: pip install platformio
      - name: Build client with PlatformIO
        run: make client.build