name: test
on:
  push:
  workflow_dispatch:
jobs:
  server:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    env:
      NUGET_USERNAME: ${{ secrets.NUGET_GITHUB_USER }}
      NUGET_PASSWORD: ${{ secrets.NUGET_GITHUB_TOKEN }}
    services:
      mariadb:
        image: mariadb:10.8.3
        env:
          MARIADB_DATABASE: grow
          MARIADB_ROOT_PASSWORD: password
        ports:
          - 3306:3306
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: Run database migrations
        run: make server.migrations.upgrade
      - name: Test server with xunit
        run: make server.test
  client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install PlatformIO
        run: pip install platformio
      - name: Run tests with unity
        run: make client.test
  app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies with npm
        run: make app.install
      - name: Run tests with vitest
        run: make app.test